const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Competition = sequelize.define('Competition', {
  id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
  title: { type: DataTypes.STRING, allowNull: false },
  subtitle: { type: DataTypes.STRING },
  eventDate: { type: DataTypes.DATEONLY, field: 'event_date' },
  eventEndDate: { type: DataTypes.DATEONLY, field: 'event_end_date' },
  registrationOpenAt: { type: DataTypes.DATE, field: 'registration_open_at' },
  registrationCloseAt: { type: DataTypes.DATE, field: 'registration_close_at' },
  location: { type: DataTypes.STRING },
  organizer: { type: DataTypes.STRING },
  imageUrl: { type: DataTypes.STRING, field: 'image_url' },
  capacity: { type: DataTypes.INTEGER, defaultValue: 50 },
  fee: { type: DataTypes.INTEGER, defaultValue: 0 },
  level: { type: DataTypes.STRING },
  stageCount: { type: DataTypes.INTEGER, defaultValue: 0, field: 'stage_count' },
  minShots: { type: DataTypes.INTEGER, defaultValue: 0, field: 'min_shots' },
  matchTypeId: { type: DataTypes.UUID, field: 'match_type_id' },
  divisionIds: { type: DataTypes.JSONB, defaultValue: [], field: 'division_ids' },
  categories: { type: DataTypes.JSONB, defaultValue: [] },
  squads: { type: DataTypes.JSONB, defaultValue: [] },
  schedule: { type: DataTypes.JSONB, defaultValue: [] },
  about: { type: DataTypes.TEXT },
  prizes: { type: DataTypes.TEXT },
  rules: { type: DataTypes.TEXT },
  requirements: { type: DataTypes.JSONB, defaultValue: [] },
  refundPolicy: { type: DataTypes.JSONB, defaultValue: [], field: 'refund_policy' },
  extraInfo: { type: DataTypes.TEXT, field: 'extra_info' },
  mdName: { type: DataTypes.STRING, field: 'md_name' },
  mdPhone: { type: DataTypes.STRING, field: 'md_phone' },
  mdEmail: { type: DataTypes.STRING, field: 'md_email' },
  squadCapacity: { type: DataTypes.INTEGER, defaultValue: 8, field: 'squad_capacity' },
  squadsPerShift: { type: DataTypes.INTEGER, defaultValue: 3, field: 'squads_per_shift' },
  lateRegistrationNote: { type: DataTypes.TEXT, field: 'late_registration_note' },
  facts: { type: DataTypes.JSONB, defaultValue: [] },
  tags: { type: DataTypes.ARRAY(DataTypes.STRING), defaultValue: [] },
  status: { type: DataTypes.ENUM('upcoming', 'open', 'past'), defaultValue: 'upcoming' },
});

module.exports = Competition;
